spring:
  application:
    name: portfolio-risk-model
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio-risk
    username: portfolio
    password: ${DB_PASSWORD:changemelater}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    debug: true

jwt:
  secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

